#!/usr/bin/env python3
"""Regenerate the ingestion register from the intake ledger.

Source documents live under raw/ but are deliberately kept out of git (they stay as
plain files on this Mac). So the "when was this ingested" record cannot come from git
history. Instead the runner appends one row per newly filed document to
archive/ingestion-ledger.csv, and this script turns that ledger plus the current raw/
tree into a readable register.

Outputs:
  wiki/ingestion-register.md   human-readable (stats + latest documents)
  wiki/ingestion-register.csv  complete dataset (sortable in Excel or Numbers)

Deterministic: output depends only on the ledger and raw/, so re-running with nothing
new yields no change. Run from the wiki folder:
  python3 scripts/build_ingestion_register.py
"""
import collections
import csv
import datetime
import os

LEDGER = "archive/ingestion-ledger.csv"
OUT_MD = "wiki/ingestion-register.md"
OUT_CSV = "wiki/ingestion-register.csv"
RECENT_N = 500
SKIP_DIRS = {"inbox", "_intake"}
SKIP_FILES = {".gitkeep", ".DS_Store", "README.md"}


def esc(s):
    return (s or "").replace("|", "\\|")


def folder(p):
    parts = p.split("/")
    return "raw/" + parts[1] if len(parts) > 2 else os.path.dirname(p) or p


def current_sources():
    """Every filed document under raw/, as repo-relative paths."""
    found = []
    if not os.path.isdir("raw"):
        return found
    for dirpath, dirnames, files in os.walk("raw"):
        rel = os.path.relpath(dirpath, "raw")
        top = rel.split(os.sep)[0]
        if top in SKIP_DIRS:
            dirnames[:] = []
            continue
        dirnames[:] = sorted(d for d in dirnames if not d.startswith("."))
        for fn in sorted(files):
            if fn in SKIP_FILES or fn.startswith(".") or fn.startswith("Icon"):
                continue
            found.append(os.path.join(dirpath, fn).replace(os.sep, "/"))
    return found


def read_ledger():
    """path -> (ingested timestamp, run id). Earliest entry for a path wins."""
    first = {}
    if not os.path.exists(LEDGER):
        return first
    with open(LEDGER, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            p = (row.get("path") or "").strip()
            ts = (row.get("ingested") or "").strip()
            if p and ts and (p not in first or ts < first[p][0]):
                first[p] = (ts, (row.get("run") or "").strip())
    return first


def main():
    present = current_sources()
    ledger = read_ledger()
    items = []
    for p in present:
        if p in ledger:
            ts, run = ledger[p]
        else:
            # Filed before the ledger existed, or added by hand: fall back to the file's
            # own modification date and say so.
            ts = datetime.datetime.fromtimestamp(os.path.getmtime(p)).strftime("%Y-%m-%d %H:%M")
            run = "untracked"
        items.append((p, ts, run))
    items.sort(key=lambda x: (x[1], x[0]), reverse=True)

    total = len(items)
    newest = items[0][1][:10] if items else datetime.date.today().isoformat()
    oldest = items[-1][1][:10] if items else newest
    byfolder = collections.Counter(folder(p) for p, _, _ in items)
    bymonth = collections.Counter(ts[:7] for _, ts, _ in items)

    os.makedirs("wiki", exist_ok=True)
    with open(OUT_CSV, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f, lineterminator="\n")
        w.writerow(["ingested", "document", "folder", "run"])
        for p, ts, run in items:
            w.writerow([ts, p, folder(p), run])

    lines = [
        "---",
        "title: Ingestion Register",
        "type: summary",
        "tags: [how-it-runs, audit, index]",
        "sources: []",
        "status: active",
        f"updated: {newest}",
        "---",
        "",
        "Every source document currently filed under `raw/`, newest first, with when the",
        "runner filed it. Generated by `scripts/build_ingestion_register.py` after every",
        "run; do not edit by hand. The full list is in `ingestion-register.csv`.",
        "",
        f"**Documents:** {total}  ·  **Span:** {oldest} to {newest}",
        "",
    ]
    if total:
        lines += ["## At a glance", "", "| Folder | Documents |", "|---|---|"]
        for k, n in byfolder.most_common():
            lines.append(f"| `{k}` | {n} |")
        lines += ["", "| Month | Documents |", "|---|---|"]
        for k, n in sorted(bymonth.items(), reverse=True):
            lines.append(f"| {k} | {n} |")
        lines += [
            "",
            f"## Latest documents (most recent {min(RECENT_N, total)})",
            "",
            "| Filed | Document | Folder |",
            "|---|---|---|",
        ]
        for p, ts, _ in items[:RECENT_N]:
            lines.append(f"| {ts} | {esc(p)} | `{folder(p)}` |")
    else:
        lines.append("No documents filed yet. Drop one into **Wiki Intake** to start.")
    lines.append("")
    with open(OUT_MD, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"register: docs={total} ledger={len(ledger)} span {oldest}->{newest}")


if __name__ == "__main__":
    main()
